---
title: "grand_function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set working directory
setwd("~/your-path/OSF-folder/r_code")

#1.00 eller 1.07
require(devtools)
install_version(, version = "1.0.7"

Loading data
```{r}
#packageurl <- "https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_1.0.0.tar.gz"
#install.packages(packageurl, repos=NULL, type="source")
#packageVersion("dplyr")

source("grand_function.R")
egemaps_dk <- read.csv("../data/R_data/egemaps_dk.csv", sep=",")
egemaps_us <- read.csv("../data/R_data/egemaps_us.csv", sep=",")
demodata   <- read.csv("../data/R_data/DemoData.csv", sep=",")

# remove index (X) collumn
egemaps_dk <- egemaps_dk[,2:ncol(egemaps_dk)]
egemaps_us <- egemaps_us[,2:ncol(egemaps_us)]


```

###Run on combinations###
dk, stories 
```{r}
source("grand_function.R")
grand_function(features = egemaps_dk, 
               other_dataframe = egemaps_us, 
               demo = demodata, 
               lang = "dk", 
               task = "stories", 
               featureset = "egemaps",
               n_lasso_folds = 5)

```

dk, triangles
```{r}
grand_function(features = egemaps_dk, 
               other_dataframe = egemaps_us, 
               demo = demodata, 
               lang = "dk", 
               task = "triangles", 
               featureset = "egemaps",
               n_lasso_folds = 5)
```

us, stories
```{r}
grand_function(features = egemaps_us, 
               other_dataframe = egemaps_dk, 
               demo = demodata, 
               lang = "us", 
               task = "stories", 
               featureset = "egemaps",
               n_lasso_folds = 5)
```


